version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    resource_class: xlarge
    steps:
      - checkout

      - run:
          name: Source Vars
          command: |
            source vars.sh
      
      - run:
          name: Source apt
          command: |
            source apts.sh

      - run:
          name: Sync
          command: |
            bash sync.sh

      - run:
          name: Build
          command: |
            bash build.sh

      - run:
          name: Upload
          command: |
            export TIMEOUT=43200
            bash upload.sh
